export const FETCH_POKEDEX = 'FETCH_POKEDEX';
export const LOAD_MORE_POKEDEX = 'LOAD_MORE_POKEDEX';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const SELECT_POKEMON = 'SELECT_POKEMON';
export const SET_QUERY = 'SET_QUERY';
export const TOGGLE_INPUT = 'TOGGLE_INPUT';
